# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push]

jobs:
  lint:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install flake
        run: pip install flake8
      - name: Run flake8
        run: flake8
    
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Get pip cache path
      run: |
        python -m pip install --upgrade pip
        pip cache dir
        echo "::set-env name=pip_cache_dir::`pip cache dir`"
    - name: Cache Python Environment and pip
      uses: actions/cache@v2
      env:
        cache-name: cache-venv-pip
      with:
        path:
          - ${{ pip_cache_dir }}
          - .venv
        key: ${{ env.cache-name }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry --version
        poetry config virtualenvs.in-project true
        poetry install -vv --extras "excel parquet"
    - name: Test with pytest
      run: |
        poetry run pytest
